language: python
python:
  - 3.4
  - 3.5
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - cd blog && coverage run --source='.'  --omit='blog/wsgi.py' manage.py test
after_success:
  coveralls