language: python
python:
  - 3.4
  - 3.5
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
script:
  - cd blog && coverage run --source='.'  --omit='blog/wsgi.py' manage.py test
after_success:
  coveralls